CourseCRM/Models/Lead.cs
using CourseCRM.Helpers;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CourseCRM.Models
{
    public class Lead
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "O nome é obrigatório")]
        [MinLength(3, ErrorMessage = "O nome deve ter no minimo 3 caracteres")]
        public string Name { get; set; } = default!;

        [Required(ErrorMessage = "O email é obrigatório")]
        [DataType(DataType.EmailAddress)]
        [EmailAddress(ErrorMessage = "Digite um email válido")]
        // Regex do Email https://regexr.com/3e48o
        [RegularExpression("^[\\w-\\.]+@([\\w-]+\\.)+[\\w-]{2,6}$", ErrorMessage = "Digite um email válido")]
        public string Email { get; set; } = default!;

        [Required(ErrorMessage = "O CPF é obrigatório")]
        [MinLength(11, ErrorMessage = "O CPF deve ter no mínimo 11 números")]
        [AnnotationValidateCpf(ErrorMessage = "CPF Inválido")]
        public string Cpf { get; set; } = default!;

        [NotMapped]
        public List<Enrollment>? Enrollments { get; set; } = default!;

        public string FormatCpf()
        {
            // Formatação de CPF http://www.codigoexpresso.com.br/Home/Postagem/28
            return Convert.ToUInt64(Cpf).ToString(@"000\.000\.000\-00");
        }
    }
}

CourseCRM/Controllers/EnrollmentsController.cs
using CourseCRM.Models;
using CourseCRM.Repository;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace CourseCRM.Controllers
{
    public class EnrollmentsController : Controller
    {
        private readonly CourseContext _context;

        public EnrollmentsController(CourseContext context)
        {
            _context = context;
        }


        public async Task<IActionResult> Index()
        {
            var courseContext = _context.Enrollment.Include(e => e.Course).Include(e => e.Lead);
            return View(await courseContext.ToListAsync());
        }


        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Enrollment == null)
            {
                return NotFound();
            }

            var enrollment = await _context.Enrollment
                .Include(e => e.Course)
                .Include(e => e.Lead)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (enrollment == null)
            {
                return NotFound();
            }

            return View(enrollment);
        }


        public IActionResult Create()
        {
            ViewData["CourseId"] = new SelectList(_context.Course, "Id", "Name");
            ViewData["LeadId"] = new SelectList(_context.Leads, "Id", "Email");
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,CourseId,LeadId,Registration")] Enrollment enrollment)
        {
            try
            {
                enrollment.Lead = _context.Leads.Where(l => l.Id == enrollment.LeadId).FirstOrDefault();
                enrollment.Course = _context.Course.Where(l => l.Id == enrollment.CourseId).FirstOrDefault();
                if (ModelState.IsValid)
                {
                    _context.Enrollment.Add(enrollment);
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
                ViewData["CourseId"] = new SelectList(_context.Course, "Id", "Name", enrollment.CourseId);
                ViewData["LeadId"] = new SelectList(_context.Leads, "Id", "Email", enrollment.LeadId);
                return View(enrollment);
            }
            catch (Exception)
            {

                TempData["MensagemErro"] = $"Não foi possível realizar a Matrícula, tente novamante!" +
                    $"\nVocê provavelmente está tentando matricular um Aluno em uma matéria a qual ele já está matriculado!";
                ViewData["CourseId"] = new SelectList(_context.Course, "Id", "Name", enrollment.CourseId);
                ViewData["LeadId"] = new SelectList(_context.Leads, "Id", "Email", enrollment.LeadId);
                return View(enrollment);
            }

        }


        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Enrollment == null)
            {
                return NotFound();
            }

            var enrollment = await _context.Enrollment
                .Include(e => e.Course)
                .Include(e => e.Lead)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (enrollment == null)
            {
                return NotFound();
            }

            return View(enrollment);
        }


        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Enrollment == null)
            {
                return Problem("Entity set 'CourseContext.Enrollment'  is null.");
            }
            var enrollment = await _context.Enrollment.FindAsync(id);
            if (enrollment != null)
            {
                _context.Enrollment.Remove(enrollment);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction("Index", "Home");
        }

        private bool EnrollmentExists(int id)
        {
            return _context.Enrollment.Any(e => e.Id == id);
        }
    }
}

CourseCRM/Controllers/LeadController.cs
using CourseCRM.Models;
using CourseCRM.Repository;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace CourseCRM.Controllers
{
    public class LeadController : Controller
    {

        private readonly ICourseRepository _courseRepository;

        public LeadController(ICourseRepository courseRepository)
        {
            _courseRepository = courseRepository;
        }
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Details(int id)
        {
            Lead? lead = _courseRepository.GetLeadAndEnrollment(id);
            if (lead == null)
            {
                return NotFound();
            }
            return View(lead);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create([Bind("Id,Name,Email,Cpf")] Lead lead)
        {
            try
            {
                if (ModelState.IsValid)
                {

                    lead = _courseRepository.CreateLeader(lead);

                    TempData["MensagemSucesso"] = "Usuário cadastrado com sucesso!";
                    return RedirectToAction("Index", "Home");
                }

                return View(lead);
            }
            catch (Exception)
            {
                TempData["MensagemErro"] = $"Não foi possível cadastrar seu usuário, tente novamante!" +
                    $"\nProvavelmente já existe um estudante com esse Email ou CPF!";
                return View(lead);
            }
        }
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            Lead? lead = _courseRepository.GetLead(id);
            return View(lead);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int? id, [Bind("Id,Email,Name,Cpf")] Lead lead)
        {
            try
            {
                if (id != lead.Id)
                {
                    return NotFound();
                }

                if (ModelState.IsValid)
                {
                    try
                    {
                        _courseRepository.EditLeader(lead);
                        return RedirectToAction("Index", "Home");
                    }
                    catch (DbUpdateConcurrencyException)
                    {
                        if (!_courseRepository.LeadExists(id))
                        {
                            return NotFound();
                        }
                        else
                        {
                            throw;
                        }
                    }
                }
                return View(lead);
            }
            catch (Exception)
            {

                TempData["MensagemErro"] = $"Não foi possível editar seu curso, tente novamante!" +
                   $"\nProvavelmente está Registrar dados iguais";
                return RedirectToAction("Index", "Home");
            }
        }

        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Lead? lead = _courseRepository.GetLead(id);
            if (lead == null)
            {
                return NotFound();
            }

            return View(lead);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Lead? lead = _courseRepository.GetLead(id);
            if (lead != null)
            {
                _courseRepository.DeleteLeader(lead);
            }

            return RedirectToAction("Index", "Home");
        }
    }
}

CourseCRM/Views/Lead/Create.cshtml
@model Lead
@{
    ViewData["Title"] = "CreateLeader";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="text-center">
    <h1 class="display-4">Cadastrar um novo Estudante</h1>
</div>


<div class="text-center">
    <h3 class="display-8 fw-bold">Digite seus dados</h3>
</div>

<br />

@if (TempData["MensagemErro"] != null)
{
        <div class="alert alert-danger" role="alert">
            <button type="button" class="btn btn-danger btn-sm close-alert position-absolute top-0 end-0" data-bs-dismiss="alert" aria-label="Close">X</button>
        @TempData["MensagemErro"]
        </div>
}

<form asp-controller="Lead" asp-action="Create" method="post">

    <div class="form-group">
        <label for="nome" class="form-label">Nome</label>
        <input type="text" asp-for="Name" class="form-control" placeholder="Digite o nome do estudante">
        @Html.ValidationMessageFor(x => x.Name, null, new { @class = "text-danger" })
    </div>

    <div class="form-group mt-2">
        <label for="nome" class="form-label">E-mail</label>
        <input type="text" asp-for="Email" class="form-control" placeholder="Digite o e-mail do estudante">
        @Html.ValidationMessageFor(x => x.Email, null, new { @class = "text-danger" })
    </div>

    <div class="form-group mt-2">
        <label for="nome" class="form-label">CPF (Somente os números)</label>
        <input max="11" min="11" type="text" asp-for="Cpf" class="form-control" placeholder="Digite o CPF do estudante(Somente os números)">
        @Html.ValidationMessageFor(x => x.Cpf, null, new { @class = "text-danger" })

    </div>

    <div class="mt-3">
        <button type="submit" class="btn btn-success btn-block">Adicionar</button>
        <a class="btn btn-secondary btn-block" asp-controller="Home" asp-action="Index" role="button">Voltar</a>
    </div>

</form>

CourseCRM/Views/Lead/CreateLeader.cshtml
@model Lead
@{
    ViewData["Title"] = "CreateLeader";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="text-center">
    <h1 class="display-4">Cadastrar um novo Estudante</h1>
</div>


<div class="text-center">
    <h3 class="display-8 fw-bold">Digite seus dados</h3>
</div>

<br />

@if (TempData["MensagemErro"] != null)
{
        <div class="alert alert-danger" role="alert">
            <button type="button" class="btn btn-danger btn-sm close-alert position-absolute top-0 end-0" data-bs-dismiss="alert" aria-label="Close">X</button>
        @TempData["MensagemErro"]
        </div>
}

<form asp-controller="Home" asp-action="CreateLeader" method="post">

    <div class="form-group">
        <label for="nome" class="form-label">Nome</label>
        <input type="text" asp-for="Name" class="form-control" placeholder="Digite o nome do estudante">
        @Html.ValidationMessageFor(x => x.Name, null, new { @class = "text-danger" })
    </div>

    <div class="form-group mt-2">
        <label for="nome" class="form-label">E-mail</label>
        <input type="text" asp-for="Email" class="form-control" placeholder="Digite o e-mail do estudante">
        @Html.ValidationMessageFor(x => x.Email, null, new { @class = "text-danger" })
    </div>

    <div class="form-group mt-2">
        <label for="nome" class="form-label">CPF (Somente os números)</label>
        <input max="11" min="11" type="text" asp-for="Cpf" class="form-control" placeholder="Digite o CPF do estudante(Somente os números)">
        @Html.ValidationMessageFor(x => x.Cpf, null, new { @class = "text-danger" })

    </div>

    <div class="mt-3">
        <button type="submit" class="btn btn-success btn-block ">Adicionar</button>
        <a class="btn btn-secondary btn-block" asp-action="Index" asp-controller="Home" role="button">Voltar</a>
    </div>

</form>

CourseCRM/Views/Lead/Delete.cshtml
@model Lead

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Deletar o Estudante</h1>

<h3>Você deseja realmente <b>deletar</b> esse curso?</h3>
<div>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            Nome
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class="col-sm-2">
            Email
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class="col-sm-2">
            CPF
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Cpf)
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Deletar" class="btn btn-danger" /> |
        <a asp-action="Index" role="button" class="btn btn-primary">Voltar para os Cursos</a>
    </form>
</div>

CourseCRM/Views/Lead/Details.cshtml
@model CourseCRM.Models.Lead
@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Detalhes do Estudante</h1>

<div>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            Nome
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class="col-sm-2">
            CPF
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Cpf)
        </dd>
        <dt class="col-sm-2">
            Email
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
    </dl>
    @if (Model.Enrollments != null && Model.Enrollments.Count > 0)
    {
        <table class="table">
            <thead>
                <tr>
                    <th>Curso</th>
                    <th>Data da Matrícula</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.Enrollments)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Course!.Name)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Registration)
                        </td>
                        <td>
                            <a asp-controller="Enrollments" asp-action="Details" class="btn btn-warning" style="color: floralwhite" role="button" asp-route-id="@item.Id">Detalhes</a> |
                            <a asp-controller="Enrollments" asp-action="Delete" class="btn btn-danger" role="button" asp-route-id="@item.Id">Deletar</a>
                        </td>
                    </tr>
                }


            </tbody>
        </table>
    } else {

        <h4 class="display-6 text-center">Você não está Matrículado em nenhum curso</h4>
    }
            
   
</div>
<div>
    <a asp-controller="Home" asp-action="Index" role="button" class="btn btn-primary">Voltar a Lista de Estudantes</a>
</div>

CourseCRM/Views/Lead/Edit.cshtml
@model CourseCRM.Models.Lead

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Editar</h1>

@if (TempData["MensagemErro"] != null)
{
    <div class="alert alert-danger" role="alert">
        <button type="button" class="btn btn-danger btn-sm close-alert position-absolute top-0 end-0" data-bs-dismiss="alert" aria-label="Close">X</button>
        @TempData["MensagemErro"]
    </div>
}

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <input asp-for="Cpf" type="hidden" class="form-control" />
            <div class="form-group">
                <input type="submit" value="Salvar" class="btn btn-success" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-controller="Home" asp-action="Index" role="button" class="btn btn-primary">Voltar a Lista de Estudantes</a>
</div>